shellEmulator: true

trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar@4.0.3
  - semver@6.3.1
  - undici-types@6.21.0
  - prisma@7.10.0

packages:
  - apps/*
  - packages/*

allowBuilds:
  '@parcel/watcher': false
  '@prisma/engines': false
  '@swc/core': false
  bcrypt: false
  prisma: false
  sharp: false
  unrs-resolver: false
