/* DO NOT EDIT, file generated by nestjs-i18n */

/* eslint-disable */
/* prettier-ignore */
import type { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "auth": {
        "unauthorized": string;
        "passwordAlreadySet": string;
        "passwordNotSet": string;
        "currentPasswordInvalid": string;
        "passwordRemovalRequiresProvider": string;
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
